### ISSUE TITLE
Error: Tag '{%' was not properly terminated with regexp: /\%\}/

### ISSUE THREAD

**Issue by richb-hanover** [comsysto/jekyll-breadcrumb-for-github-pages#2]
I'm having trouble making the breadcrumb facility work. I get the following message when I  check out the full repo and try to run it.

What other information could I provide?

```
bash-3.2$ cd github/jekyll-breadcrumb-for-github-pages/
bash-3.2$ git status
On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
nothing to commit, working directory clean
bash-3.2$ jekyll serve
Configuration file: /Users/richb/github/jekyll-breadcrumb-for-github-pages/_config.yml
            Source: /Users/richb/github/jekyll-breadcrumb-for-github-pages
       Destination: /Users/richb/github/jekyll-breadcrumb-for-github-pages/_site
      Generating...
  Liquid Exception: Tag '{%' was not properly terminated with regexp: /\%\}/ in _includes/header.html, included in _layouts/default.html
jekyll 2.4.0 | Error:  Tag '{%' was not properly terminated with regexp: /\%\}/
```

**Comment by offboarded-x233534** [comment]
I will check that. Maybe it has become defunct due to latest jekyll 3 upgrade.
I will get back to you once I tested it out.

**Comment by offboarded-x233534** [comment]
ok I just checked it out and I don't get an error and my breadcrumb renders fine.
I am using jekyll version 3.1.3. Maybe try to upgrade jekyll https://jekyllrb.com/docs/upgrading/

```
$ jekyll --version
jekyll 3.1.3
```

![breadcrumb](https://cloud.githubusercontent.com/assets/9586869/15318815/2c156c76-1c28-11e6-955d-8c20f0ad4f02.gif)

**Comment by richb-hanover** [comment]
Yes, upgrading from jekyll 2.something to version 3.1.3 gets rid of this problem. Thanks.
